apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperparams-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MLFLOW_TRACKING_URI: http://mlflow:5000
  STUDY_NAME: {{ .Values.worker.studyName }}
  MAX_EPOCHS: {{ .Values.worker.maxEpochs | quote }}
  PRUNER_TYPE: {{ .Values.worker.prunerType }}
  N_TRIALS: {{ .Values.worker.trialsPerWorker | quote }}
  LR_LOW: {{ .Values.searchSpace.lrLow | quote }}
  LR_HIGH: {{ .Values.searchSpace.lrHigh | quote }}
  BATCH_SIZES: {{ .Values.searchSpace.batchSizes | quote }}
  NUM_LAYERS_LOW: {{ .Values.searchSpace.numLayersLow | quote }}
  NUM_LAYERS_HIGH: {{ .Values.searchSpace.numLayersHigh | quote }}
  DROPOUT_LOW: {{ .Values.searchSpace.dropoutLow | quote }}
  DROPOUT_HIGH: {{ .Values.searchSpace.dropoutHigh | quote }}
  OPTIMIZERS: {{ .Values.searchSpace.optimizers | quote }}
